using ReportBuilder.Abstractions.Interfaces;
using ReportBuilder.Abstractions;

namespace ReportBuilder.Builders
{
    public class JsonReportBuilder : IReportBuilder
    {
        private Report _report = new();

        public void BuildHeader()
        {
            _report.Header = "{\"title\": \"JSON Financial Report\"}";
        }

        public void BuildBody()
        {
            _report.Body = "{\"revenue\":1000000,\"expenses\":400000}";
        }

        public void BuildFooter()
        {
            _report.Footer = "{\"note\": \"Generated by system\"}";
        }

        public Report GetReport() => _report;
    }
}
